import { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import '@material/web/button/filled-button.js';
import '@material/web/button/outlined-button.js';
import { TopBar } from '../components/TopBar/TopBar';
import { useToast } from '../components/LayerSystem/LayerSystem';
import { apiClient } from '../services/api';
import type { CustomModelSettings, HermesSettings } from '../services/api';
import './UserSettings.css';

export function ModelSettings() {
  const navigate = useNavigate(); const showToast = useToast();
  const [memberType, setMemberType] = useState('free');
  const [custom, setCustom] = useState<CustomModelSettings>({ enabled: false, base_url: '', model: '', daily_enabled: false, expert_enabled: false, search_enabled: false, has_api_key: false });
  const [customKey, setCustomKey] = useState(''); const [customBusy, setCustomBusy] = useState<'test' | 'save' | null>(null);
  const [hermes, setHermes] = useState<HermesSettings>({ base_url: '', model: '', has_api_key: false, tested: false, context_version: 0 });
  const [hermesKey, setHermesKey] = useState(''); const [hermesBusy, setHermesBusy] = useState<'test' | 'save' | null>(null);
  useEffect(() => { void apiClient.getProfile().then(u => setMemberType(u.member_type || 'free')); void apiClient.getCustomModel().then(setCustom).catch(console.error); void apiClient.getHermes().then(setHermes).catch(console.error); }, []);

  const testCustom = async () => { setCustomBusy('test'); try { const result = await apiClient.testCustomModel({ base_url: custom.base_url, api_key: customKey || undefined, model: custom.model }); setCustom(v => ({ ...v, has_api_key: v.has_api_key || !!customKey, response_mode: result.response_mode, last_tested_at: result.last_tested_at })); setCustomKey(''); showToast({ tone: 'success', message: '连接成功' }); } catch (error) { showToast({ tone: 'error', message: error instanceof Error ? error.message : '连通性检测失败' }); } finally { setCustomBusy(null); } };
  const saveCustom = async () => { setCustomBusy('save'); try { setCustom(await apiClient.updateCustomModel({ ...custom, api_key: customKey || undefined })); setCustomKey(''); showToast({ tone: 'success', message: '自定义模型设置已保存' }); } catch (error) { showToast({ tone: 'error', message: error instanceof Error ? error.message : '保存失败' }); } finally { setCustomBusy(null); } };
  const actHermes = async (test: boolean) => { setHermesBusy(test ? 'test' : 'save'); try { const data = { base_url: hermes.base_url, model: hermes.model, api_key: hermesKey || undefined }; setHermes(test ? await apiClient.testHermes(data) : await apiClient.updateHermes(data)); setHermesKey(''); showToast({ tone: 'success', message: test ? 'Hermes 连接成功' : 'Hermes 配置已保存' }); } catch (error) { showToast({ tone: 'error', message: error instanceof Error ? error.message : 'Hermes 操作失败' }); } finally { setHermesBusy(null); } };

  return <div className="app-container"><div className="main-content"><TopBar conversationTitle="模型与 Hermes" showBackButton onBack={() => navigate('/settings')} userMemberType={memberType} showBrand={false} /><div className="settings-page-container"><div className="settings-sections">
    <section className="settings-section"><h3 className="section-title">自定义模型</h3><div className="custom-model-card"><label className="custom-master-switch"><span><strong>启用自定义模型</strong><small>成功调用时不消耗 Credits</small></span><input type="checkbox" checked={custom.enabled} onChange={e => setCustom({ ...custom, enabled: e.target.checked })} /></label><div className="custom-model-fields"><label>Base URL<input type="url" value={custom.base_url} onChange={e => setCustom({ ...custom, base_url: e.target.value, response_mode: '' })} /></label><label>API Key<input type="text" autoComplete="off" placeholder={custom.has_api_key ? '已保存，留空则不修改' : '请输入 API Key'} value={customKey} onChange={e => { setCustomKey(e.target.value); setCustom({ ...custom, response_mode: '' }); }} /></label><label>Model<input type="text" value={custom.model} onChange={e => setCustom({ ...custom, model: e.target.value, response_mode: '' })} /></label></div><div className="custom-scopes">{([['daily_enabled','日常模式'],['expert_enabled','专家模式'],['search_enabled','联网搜索']] as const).map(([key,label]) => <label key={key}><input type="checkbox" disabled={!custom.enabled} checked={custom[key]} onChange={e => setCustom({ ...custom, [key]: e.target.checked })} />{label}</label>)}</div><div className="custom-model-status">{custom.response_mode ? `已通过检测 · ${custom.response_mode === 'stream' ? '流式输出' : '非流式输出'}` : '修改连接信息后需要重新检测'}。图片能力仍使用项目模型并扣费。</div><div className="custom-model-actions"><md-outlined-button onClick={testCustom} disabled={!!customBusy}>{customBusy === 'test' ? '检测中...' : '测试连接'}</md-outlined-button><md-filled-button onClick={saveCustom} disabled={!!customBusy || (custom.enabled && !custom.response_mode)}>{customBusy === 'save' ? '保存中...' : '保存配置'}</md-filled-button></div></div></section>
    <section className="settings-section"><h3 className="section-title">Hermes Agent</h3><div className="custom-model-card"><div className="custom-model-fields"><label>Base URL<input type="url" value={hermes.base_url} onChange={e => setHermes({ ...hermes, base_url: e.target.value, tested: false })} /></label><label>API Key<input type="text" autoComplete="off" placeholder={hermes.has_api_key ? '已保存，留空则不修改' : '请输入 API Key'} value={hermesKey} onChange={e => { setHermesKey(e.target.value); setHermes({ ...hermes, tested: false }); }} /></label><label>Model<input type="text" value={hermes.model} onChange={e => setHermes({ ...hermes, model: e.target.value, tested: false })} /></label></div><div className="custom-model-status">{hermes.tested ? '已通过流式连接检测，可在聊天中使用' : '保存前请先测试连接'}。请求仅发送到你的 Hermes 主机，不消耗 Credits。</div><div className="custom-model-actions"><md-outlined-button disabled={!!hermesBusy} onClick={() => actHermes(true)}>{hermesBusy === 'test' ? '检测中...' : '测试连接'}</md-outlined-button><md-filled-button disabled={!!hermesBusy || !hermes.tested} onClick={() => actHermes(false)}>{hermesBusy === 'save' ? '保存中...' : '保存配置'}</md-filled-button></div></div></section>
  </div></div></div></div>;
}
